### ISSUE TITLE
Bug? Local var instead instance.

### ISSUE THREAD

**Issue by ErnestK** [kinderly/expertsender_api#5]
Hello, @beorc 

I think this is bug in initialize block:
https://github.com/kinderly/expertsender_api/blob/master/lib/expertsender_api/api.rb#L25

we should compare instance var "@api_endpoint", because we dont init local var with that name.
All if block never run.
Or I mistake?

**Comment by beorc** [comment]
`api_endpoint` refers to the method actually, not a variable.

**Comment by kovalevsky** [comment]
`api_endpiont` is `attr_accessor`, so following code have to work correctly.
Did you face init issue? or did you just review code and want to clarify if it's working correctly?

**Comment by ErnestK** [comment]
thank you, 
you right, my mistake.
